name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 每次向 main 分支推送代码时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/configure-pages@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # 将编译出的静态文件夹上传

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4